"""Falsification stubs: claim 'content-addressed skip solution is done.'

Generated by falsification audit 2026-06-09. Resolved by #144 fix.
F-1: ADR-041 claims 'every run records a ledger entry' with three
outcomes (success, unchanged, failed). Fixed: both scripts use
try/finally to write outcome='failed' on ALL exit paths (return 1,
exceptions, and unhandled crashes). The finally block fires on every
exit, eliminating the coverage gaps of the earlier helper approach.
"""

from __future__ import annotations

from pathlib import Path


class TestF1FailedOutcomeContract:
    """F-1: Assembly and export must write outcome='failed'."""

    def test_assembly_writes_failed_on_crash(self) -> None:
        content = Path("scripts/assemble_grid.py").read_text()
        assert '"failed"' in content, (
            "assemble_grid.py has no code path that writes "
            "outcome='failed' to the ledger"
        )

    def test_export_writes_failed_on_crash(self) -> None:
        content = Path("scripts/export_zarr.py").read_text()
        assert '"failed"' in content, (
            "export_zarr.py has no code path that writes "
            "outcome='failed' to the ledger"
        )

    def test_export_writes_success(self) -> None:
        content = Path("scripts/export_zarr.py").read_text()
        assert '"success"' in content, (
            "export_zarr.py has no code path that writes "
            "outcome='success' to the ledger"
        )
