"""Falsification stubs — GHS-POP 8 GB server memory safety.

Generated by /falsify audit. Each test encodes a finding that
must be resolved before the 8 GB deployment claim can be reasserted.
"""

from __future__ import annotations

import sys

import pytest


class TestF1TifffileDecompressionPeak:
    """F1 (soft): tifffile buffers ~512 MB of compressed data alongside
    the 6.88 GiB output array during page.asarray(). Peak ~7.5 GiB
    leaves near-zero headroom on 8 GiB server."""

    def test_read_geotiff_limits_decompression_threads(self) -> None:
        """_read_geotiff should pass maxworkers=1 to page.asarray()
        to avoid ThreadPoolExecutor double-buffering (~400 MB saving)."""
        import ast
        from pathlib import Path

        src = Path(
            "src/datafactory_viewpoint/builders/ghspop_v1.py"
        ).read_text()
        tree = ast.parse(src)

        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "asarray"
            ):
                kwarg_names = [kw.arg for kw in node.keywords]
                assert "maxworkers" in kwarg_names, (
                    "page.asarray() called without maxworkers=1 — "
                    "tifffile's default thread pool double-buffers "
                    "~512 MB of compressed data, pushing peak to "
                    "7.5 GiB on an 8 GiB server"
                )


class TestF2LatentOOMInAggregateToPrioGrid:
    """F2 (soft): _aggregate_to_prio_grid does data.copy() which
    doubles the array. The needs_align=False branch would trigger
    this with a raster whose dimensions are divisible by 60."""

    def test_build_always_uses_strip_aggregation(self) -> None:
        """build_ghspop_v1 should use _aggregate_with_alignment
        unconditionally, not rely on accidental JRC dimensions."""
        import ast
        from pathlib import Path

        src = Path(
            "src/datafactory_viewpoint/builders/ghspop_v1.py"
        ).read_text()
        tree = ast.parse(src)

        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if node.name != "build_ghspop_v1":
                continue
            body_src = ast.dump(node)
            assert "_aggregate_to_prio_grid" not in body_src, (
                "build_ghspop_v1 still calls _aggregate_to_prio_grid "
                "in the needs_align=False branch — this path does "
                "data.copy() on the full array (13.9 GiB peak for "
                "float64 21600x43200). Use _aggregate_with_alignment "
                "unconditionally."
            )


class TestF3ListAccumulationMemory:
    """F3 (hard): The builder accumulates three Python lists for all
    non-zero cell-months (~60M entries, ~6.5 GB). These are never
    deleted — they coexist with the Arrow table during pa.table()
    creation, pushing peak to 7.4–8.3 GB."""

    def test_lists_deleted_before_digest(self) -> None:
        """pgid_rows, month_id_rows, pop_count_rows must be deleted
        after Arrow table creation to free ~6.5 GB."""
        import ast
        from pathlib import Path

        src = Path(
            "src/datafactory_viewpoint/builders/ghspop_v1.py"
        ).read_text()
        tree = ast.parse(src)

        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if node.name != "build_ghspop_v1":
                continue

            del_targets: set[str] = set()
            for child in ast.walk(node):
                if isinstance(child, ast.Delete):
                    for target in child.targets:
                        if isinstance(target, ast.Name):
                            del_targets.add(target.id)

            for name in (
                "pgid_rows", "month_id_rows", "pop_count_rows",
            ):
                assert name in del_targets, (
                    f"{name} is never deleted in build_ghspop_v1 — "
                    f"~60M Python objects (~2 GB) remain in scope "
                    f"during Arrow table creation and digest "
                    f"computation, risking OOM on 8 GB server"
                )


class TestF5NoSwapSafetyNet:
    """F5 (soft): Hetzner CPX32 has no swap. Any transient spike
    above physical RAM triggers immediate OOM kill."""

    def test_deployment_guide_mentions_swap(self) -> None:
        """Deployment guide should document swap configuration
        as a safety net for memory-intensive pipelines."""
        from pathlib import Path

        guide = Path(
            "docs/guides/hetzner_deployment_guide.md"
        )
        if not guide.exists():
            pytest.skip("deployment guide not found")

        content = guide.read_text()
        assert "swap" in content.lower(), (
            "Deployment guide does not mention swap — the CPX32 "
            "has no swap by default, so any memory spike above "
            "8 GB triggers immediate OOM kill with no fallback"
        )


class TestF6CompilationToPylistMemory:
    """F6 (hard): compile_pregridded calls .to_pylist() on Arrow
    columns, recreating ~6 GB of Python objects alongside the
    Arrow table (~1 GB) and grid array (~0.5 GB) = ~7.7 GB peak."""

    def test_compilation_avoids_to_pylist(self) -> None:
        """compile_pregridded should use Arrow-native iteration
        or to_numpy() instead of .to_pylist() to avoid
        materialising ~6 GB of Python objects."""
        import ast
        from pathlib import Path

        src = Path(
            "src/datafactory_compilation/"
            "pregridded_compilation.py"
        ).read_text()
        tree = ast.parse(src)

        to_pylist_count = 0
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "to_pylist"
            ):
                to_pylist_count += 1

        assert to_pylist_count == 0, (
            f"compile_pregridded uses .to_pylist() {to_pylist_count} "
            f"times — each call materialises ~60M Python objects "
            f"(~2 GB per column). Use .to_numpy() or iterate over "
            f"Arrow chunks to keep peak under 2 GB."
        )


class TestF3PeakMemoryEstimate:
    """F3 supplementary: verify that the estimated number of
    non-zero output rows would exceed safe Python list capacity
    on an 8 GB server."""

    @pytest.mark.slow
    def test_list_overhead_estimate(self) -> None:
        """Python list of 60M ints should exceed 2 GB."""
        n = 60_000_000
        int_size = sys.getsizeof(1000)
        ptr_size = 8
        per_entry = int_size + ptr_size

        three_lists_gb = (3 * n * per_entry) / (1024**3)
        assert three_lists_gb > 4.0, (
            f"3 lists of {n} entries = {three_lists_gb:.1f} GiB — "
            f"expected > 4 GiB. If this passes, the memory model "
            f"is correct and lists ARE the bottleneck."
        )
