"""Falsification test stubs: V-Dem audit documentation gaps.

Generated by /falsify audit on 2026-05-26.
Claim: "All implementation decisions from V-Dem plots 11-15
are documented in the correct locations (ADRs, CICs, data
cards, guides)."

Each test encodes a specific documentation gap found during
the audit.  Tests FAIL until the gap is closed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

DOCS = Path("docs")
CICS = DOCS / "CICs"
ADRS = DOCS / "ADRs"
SOURCES = DOCS / "sources"
GUIDES = DOCS / "guides"


class TestP1PrecomputedDataCIC:
    """P-1: PrecomputedData lacks an intent contract.

    ADR-006 requires CICs for non-trivial classes that
    "maintain internal state across operations" or "could
    cause silent confusion if misunderstood."

    PrecomputedData (21 fields, behavioral invariants like
    per-feature last_valid_t for country_values) qualifies.
    ADR-006 already scopes scripts/ (lists AssemblyConfig
    from scripts/assemble_grid.py).
    """

    @pytest.mark.xfail(
        reason=(
            "P-1: No CIC for PrecomputedData — "
            "ADR-006 requires one for non-trivial "
            "classes in scripts/"
        ),
    )
    def test_precomputed_data_cic_exists(self) -> None:
        cic = CICS / "PrecomputedData.md"
        assert cic.exists(), (
            f"No CIC at {cic}. PrecomputedData has 21 "
            f"fields with behavioral invariants "
            f"(country_values uses per-feature "
            f"last_valid_t). ADR-006 scope includes "
            f"scripts/ classes."
        )


class TestP3P7ConsumerGuideScaleClassification:
    """P-3/P-7: Consumer guide omits scale classification.

    The consumer guide lists 22 V-Dem features with name
    and description only.  No scale/range information.
    5 features use interval scale [-2.3, +2.3], 17 use
    bounded [0,1].  Without this, consumers assume all
    features share the same scale.
    """

    INTERVAL_FEATURES = {
        "v2x_horacc",
        "v2x_veracc",
        "v2x_diagacc",
        "v2x_divparctrl",
        "v2x_accountability",
    }

    @pytest.mark.xfail(
        reason=(
            "P-3: Consumer guide has no scale/range "
            "info for V-Dem features"
        ),
    )
    def test_consumer_guide_has_scale_info(self) -> None:
        guide = GUIDES / "consumer_data_guide.md"
        assert guide.exists()
        text = guide.read_text()
        assert "interval" in text.lower() or "[0,1]" in text, (
            "Consumer guide V-Dem section has no scale "
            "classification (interval vs bounded [0,1]). "
            "Consumers cannot distinguish features with "
            "fundamentally different ranges."
        )

    @pytest.mark.xfail(
        reason=(
            "P-7: V-Dem data card has no scale/range "
            "info for individual features"
        ),
    )
    def test_data_card_has_scale_info(self) -> None:
        card = SOURCES / "vdem.md"
        assert card.exists()
        text = card.read_text()
        for feat in self.INTERVAL_FEATURES:
            assert feat in text and (
                "interval" in text or "[-" in text
            ), (
                f"Data card does not document {feat} as "
                f"interval-scale. Only location is code "
                f"constant INTERVAL_SCALE_FEATURES."
            )


class TestP4ExclusionTemporalLag:
    """P-4: Exclusion features' 2023 cutoff undocumented.

    4 features (v2xpe_exlsocgr, exlgeo, exlpol,
    exlgender) have data only through 2023, while all
    other features extend to 2025.  All governance docs
    state blanket coverage "1789-2025" without per-feature
    caveats.
    """

    EXCLUSION_FEATURES = [
        "v2xpe_exlsocgr",
        "v2xpe_exlgeo",
        "v2xpe_exlpol",
        "v2xpe_exlgender",
    ]

    @pytest.mark.xfail(
        reason=(
            "P-4: No governance doc mentions exclusion "
            "features ending at 2023"
        ),
    )
    def test_exclusion_lag_documented(self) -> None:
        docs_to_check = [
            ADRS / "035_vdem_as_democracy_source.md",
            SOURCES / "vdem.md",
            GUIDES / "consumer_data_guide.md",
        ]
        found = False
        for doc in docs_to_check:
            if not doc.exists():
                continue
            text = doc.read_text()
            if "2023" in text and any(
                f in text for f in self.EXCLUSION_FEATURES
            ):
                found = True
                break
        assert found, (
            "No governance doc mentions that "
            "v2xpe_exl* features end at 2023. "
            "All state blanket '1789-2025' coverage."
        )


class TestP5BroadcastInvariantFormalized:
    """P-5: Broadcast property not formalized.

    ADR-035 describes broadcast informally. ADR-024
    lists 5 compilation invariants; broadcast is not
    among them.  No CIC states within-country variance
    must be zero.
    """

    @pytest.mark.xfail(
        reason=(
            "P-5: Broadcast invariant not in ADR-024 "
            "compilation invariants"
        ),
    )
    def test_broadcast_in_compilation_invariants(
        self,
    ) -> None:
        adr = ADRS / "024_compilation_grid_invariants.md"
        assert adr.exists()
        text = adr.read_text().lower()
        assert "broadcast" in text or (
            "within-country" in text
        ), (
            "ADR-024 lists 5 compilation invariants "
            "but broadcast (within-country variance=0) "
            "is not among them."
        )
