"""Falsification stubs — GHS-POP deployment readiness (v3).

Generated by /falsify audit round 3. Each test encodes a finding
that must be resolved before the deployment claim can be reasserted.
"""

from __future__ import annotations

from pathlib import Path


class TestF1CicFailureModes:
    """F1: GhsPopConfig CIC Section 6 must list all failure modes."""

    def test_cic_section6_documents_zip_valueerror(self) -> None:
        """CIC Section 6 must mention the ValueError raised when
        ZIP contents don't match the expected TIF filename."""
        cic = Path("docs/CICs/GhsPopConfig.md")
        assert cic.exists(), "GhsPopConfig CIC not found"
        text = cic.read_text()

        section6_start = text.find("## 6.")
        section7_start = text.find("## 7.")
        assert section6_start != -1, "Section 6 not found in CIC"
        assert section7_start != -1, "Section 7 not found in CIC"

        section6 = text[section6_start:section7_start]

        assert "ZIP" in section6 or "zip" in section6, (
            "CIC Section 6 (Failure Modes) does not mention the "
            "ValueError raised on unexpected ZIP contents — "
            "Section 10 documents it but Section 6 does not"
        )


class TestF4DeploymentGuide:
    """F4: Deployment guide must mention GHS-POP."""

    def test_deployment_guide_mentions_ghspop(self) -> None:
        """The Hetzner deployment guide must reference GHS-POP
        so operators know about disk space and timing impact."""
        guide = Path("docs/guides/hetzner_deployment_guide.md")
        assert guide.exists(), "Deployment guide not found"
        text = guide.read_text().lower()
        assert "ghs-pop" in text or "ghspop" in text, (
            "Deployment guide has no GHS-POP reference — "
            "operators won't know about ~5.3 GB disk usage, "
            "~12 min added pipeline time, or that no credentials "
            "are required"
        )
