"""Falsification stubs — GHS-POP deployment readiness.

Generated by /falsify audit. Each test encodes a finding that
must be resolved before the deployment claim can be reasserted.
"""

from __future__ import annotations

import pytest


class TestF1SourceRegistryCompleteness:
    """F1: ghspop_pop_count must appear in PIPELINE_SOURCES so that
    verify_remote.py checks for it after deployment."""

    def test_ghspop_feature_in_registry(self) -> None:
        from datafactory_provenance.source_registry import (
            get_all_features,
        )

        features = get_all_features()
        assert "ghspop_pop_count" in features, (
            "ghspop_pop_count missing from PIPELINE_SOURCES — "
            "verify_remote.py won't detect missing population data"
        )

    def test_ghspop_source_entry_exists(self) -> None:
        from datafactory_provenance.source_registry import (
            PIPELINE_SOURCES,
        )

        names = [s.name for s in PIPELINE_SOURCES]
        ghspop_entries = [n for n in names if "ghs" in n.lower()]
        assert ghspop_entries, (
            "No GHS-POP SourceEntry in PIPELINE_SOURCES — "
            "SLO monitoring and preflight checks are blind to "
            "population data"
        )


class TestF2ViewpointMemory:
    """F2: viewpoint must not allocate raw + globe simultaneously as
    float64 — peak 22 GB exceeds 8 GB server RAM."""

    @pytest.mark.slow
    def test_align_to_globe_does_not_upcast_input(self) -> None:
        """Globe array should use input dtype, not unconditional float64."""
        import numpy as np

        from datafactory_viewpoint.builders.ghspop_v1 import (
            _align_to_globe,
        )

        # Simulate a small float32 raster
        data = np.ones((120, 120), dtype=np.float32)
        result = _align_to_globe(
            data,
            tiepoint_x=-180.0,
            tiepoint_y=90.0,
            pixel_scale_x=0.00833333,
            pixel_scale_y=0.00833333,
        )
        assert result.dtype == np.float32, (
            f"_align_to_globe upcast to {result.dtype} — "
            f"on real data this doubles 3.7 GB to 7.5 GB, "
            f"causing 22 GB peak on 8 GB server"
        )


class TestF5GitignoreCompleteness:
    """F5: audit_ghspop should be gitignored like audit_acled."""

    def test_audit_ghspop_gitignored(self) -> None:
        from pathlib import Path

        gitignore = Path(".gitignore")
        if not gitignore.exists():
            pytest.skip(".gitignore not found")

        content = gitignore.read_text()
        assert "audit_ghspop" in content, (
            "reports/audit_ghspop/ not in .gitignore — "
            "regenerated PNGs will pollute every future diff"
        )
