"""Falsification test stubs for claim: "GHS-BUILT-S is merge-ready for development"
Generated by /falsify audit round 2 on 2026-05-23

These tests are in TDD RED state -- they FAIL against the current code.
Fix the code to make them pass, then re-run /falsify to verify.
"""

from __future__ import annotations


def test_falsify_06_deployment_guide_download_size() -> None:
    """Probe 6 (Category E): Deployment guide claims ~5 GB download
    for GHS-BUILT-S, but ADR-034 says ~2.1 GB (12 epochs at ~178 MB).

    Finding: Guide paragraph copied from GHS-POP (~5.3 GB) without
    adjusting the download size for GHS-BUILT-S.
    Severity: hard

    Expected: Deployment guide states download size consistent with
    ADR-034 (~2.1 GB or ~2 GB).
    """
    from pathlib import Path

    guide = (
        Path(__file__).parent.parent
        / "docs" / "guides" / "hetzner_deployment_guide.md"
    )
    content = guide.read_text()

    ghsbuilts_start = content.index("**GHS-BUILT-S")
    ghsbuilts_para = content[ghsbuilts_start:ghsbuilts_start + 500]

    assert "~5 GB" not in ghsbuilts_para, (
        "Deployment guide claims ~5 GB download for GHS-BUILT-S, "
        "but ADR-034 says ~2.1 GB (12 epochs at ~178 MB each). "
        "The figure was copied from the GHS-POP paragraph."
    )


def test_falsify_07_adr008_fetch_ghsbuilts_network_error() -> None:
    """Probe 7 (Category B): ADR-008 requires logger.error before
    every raise. fetch_ghsbuilts re-raises RequestException at line 185
    without a preceding logger.error.

    Finding: bare `raise` in except RequestException block with no
    logger.error — operational failure goes unlogged.
    Severity: soft

    Expected: logger.error(...) appears before `raise` in both
    the RequestException handler (line 185) and the BadZipFile
    handler (line 205).
    """
    import ast
    from pathlib import Path

    module_path = (
        Path(__file__).parent.parent
        / "src" / "datafactory_harvester" / "sources" / "ghsbuilts.py"
    )
    source = module_path.read_text()
    tree = ast.parse(source)

    violations: list[int] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ExceptHandler):
            continue
        for i, stmt in enumerate(node.body):
            if isinstance(stmt, ast.Raise) and stmt.exc is None:
                has_log = any(
                    isinstance(s, ast.Expr)
                    and isinstance(s.value, ast.Call)
                    and hasattr(s.value.func, "attr")
                    and s.value.func.attr == "error"
                    for s in node.body[:i]
                )
                if not has_log:
                    violations.append(stmt.lineno)

    assert not violations, (
        f"ADR-008 violation: bare raise without logger.error "
        f"at lines {violations} in ghsbuilts.py"
    )
