"""Falsification stubs — GHS-POP deployment readiness (v2).

Generated by /falsify audit. Each test encodes a finding that
must be resolved before the deployment claim can be reasserted.
"""

from __future__ import annotations

import subprocess
import sys

import pytest


class TestF4UncommittedFixes:
    """F4: Critical deployment fixes must be committed before tagging."""

    def test_no_uncommitted_changes_in_deployment_files(self) -> None:
        result = subprocess.run(
            ["git", "diff", "--name-only", "--",
             "src/datafactory_viewpoint/builders/ghspop_v1.py",
             "src/datafactory_provenance/source_registry.py",
             ".gitignore"],
            capture_output=True, text=True,
        )
        dirty = [f for f in result.stdout.strip().split("\n") if f]
        assert not dirty, (
            f"Deployment-critical files have uncommitted changes: "
            f"{dirty} — commit before tagging"
        )


class TestF6TemporalEndYear:
    """F6: GHS-POP compilation should match UCDP temporal range."""

    def test_ghspop_pipeline_accepts_end_year(self) -> None:
        """run_ghspop_pipeline.py must accept --end-year like
        compile_grid.py and run_acled_pipeline.py do."""
        result = subprocess.run(
            [sys.executable, "scripts/run_ghspop_pipeline.py", "--help"],
            capture_output=True, text=True,
        )
        assert "--end-year" in result.stdout, (
            "run_ghspop_pipeline.py has no --end-year argument — "
            "GHS-POP compiles to 2024-12 while UCDP compiles to "
            "2026-12, causing 24 months of unnecessary zero-fill "
            "for population data"
        )


def _version_already_tagged() -> bool:
    from importlib.metadata import version

    current = version("views-datafactory")
    result = subprocess.run(
        ["git", "tag", "-l", f"v{current}"],
        capture_output=True, text=True,
    )
    return f"v{current}" in result.stdout.strip().split("\n")


class TestF7VersionBump:
    """F7: Version must be bumped before tagging."""

    @pytest.mark.xfail(
        condition=_version_already_tagged(),
        reason="version already tagged — expected post-deploy",
    )
    def test_version_not_already_tagged(self) -> None:
        from importlib.metadata import version

        current = version("views-datafactory")
        result = subprocess.run(
            ["git", "tag", "-l", f"v{current}"],
            capture_output=True, text=True,
        )
        existing_tags = result.stdout.strip().split("\n")
        existing_tags = [t for t in existing_tags if t]
        assert f"v{current}" not in existing_tags, (
            f"Tag v{current} already exists — bump version in "
            f"pyproject.toml before creating a new tag"
        )
