"""Falsification tests for ADR-049 epic completeness — round 2.

Generated by /falsify on 2026-06-28. These tests fail until
the identified gaps are addressed.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class TestG5GaulCrosswalkPathAlignment:
    """G5: ViewpointConfig default crosswalk paths must match
    the pipeline's output directory."""

    def test_config_default_gaul1_matches_pipeline(self) -> None:
        from datafactory_viewpoint.viewpoint_config import (
            ViewpointConfig,
        )

        config = ViewpointConfig(
            consolidated_path=Path("dummy"),
            output_path=Path("dummy"),
            ledger_path=Path("dummy"),
        )
        pipeline_dir = Path("data/raw/gaul_admin")
        expected = pipeline_dir / "gaul1_code.parquet"
        assert config.gaul1_crosswalk_path == expected, (
            f"ViewpointConfig default gaul1_crosswalk_path "
            f"({config.gaul1_crosswalk_path}) does not match "
            f"pipeline output directory ({expected}). "
            f"refresh_pipeline.sh writes to data/raw/gaul_admin/ "
            f"but config reads from "
            f"data/raw/gaul_admin_area_majority/"
        )

    def test_config_default_gaul0_matches_pipeline(self) -> None:
        from datafactory_viewpoint.viewpoint_config import (
            ViewpointConfig,
        )

        config = ViewpointConfig(
            consolidated_path=Path("dummy"),
            output_path=Path("dummy"),
            ledger_path=Path("dummy"),
        )
        pipeline_dir = Path("data/raw/gaul_admin")
        expected = pipeline_dir / "gaul0_code.parquet"
        assert config.gaul0_crosswalk_path == expected, (
            f"ViewpointConfig default gaul0_crosswalk_path "
            f"({config.gaul0_crosswalk_path}) does not match "
            f"pipeline output directory ({expected}). "
            f"refresh_pipeline.sh writes to data/raw/gaul_admin/ "
            f"but config reads from "
            f"data/raw/gaul_admin_area_majority/"
        )
