"""
Falsification tests for claim:
"The expert code review correctly identified root cause, splash zone,
and fix for the digest verification bug (C-195)."

Generated by /falsify audit on 2026-06-02.
Originally TDD RED stubs; now passing after the cache digest fix (v1.2.25).
"""

from __future__ import annotations

import json
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

from datafactory_provenance import (
    append_ledger_entry,
    compute_content_digest,
    compute_file_digest,
    last_digest_for_version,
)


class TestF1GhsPopCacheCheckNotBroken:
    """Probe #1 (Category B): GHS-POP cache check is NOT broken.

    Finding: compute_content_digest(data) and compute_file_digest(path)
    produce identical SHA-256 for the same bytes. The expert review
    incorrectly claimed GHS-POP was affected by the ACLED bug.

    Severity: hard falsification (of the review's splash zone claim)
    """

    def test_content_and_file_digest_match_for_same_bytes(
        self, tmp_path: Path,
    ) -> None:
        data = b"simulated GeoTIFF raw bytes" * 1000
        file_path = tmp_path / "test.tif"
        file_path.write_bytes(data)

        content_d = compute_content_digest(data)
        file_d = compute_file_digest(file_path)

        assert content_d == file_d, (
            f"content_digest ({content_d}) != file_digest ({file_d}) "
            f"for identical bytes — GHS-POP/GHS-BUILT-S would be broken"
        )


class TestF2AcledCacheCheckIsBroken:
    """Probe #3 (Category G): ACLED cache check IS broken.

    The content_digest in the ledger is SHA-256 of sorted event tuples
    serialized as JSON. The file digest is SHA-256 of Parquet bytes.
    These are fundamentally different values.

    Severity: hard falsification (confirms the review's core finding)
    """

    def test_acled_content_digest_differs_from_file_digest(
        self, tmp_path: Path,
    ) -> None:
        events = [
            {"event_id_cnty": f"SOM{i:04d}", "fatalities": i * 3}
            for i in range(5)
        ]

        digest_fields = ("event_id_cnty", "fatalities")
        digest_data = sorted(
            tuple(ev.get(f, 0) for f in digest_fields)
            for ev in events
        )
        content_digest = compute_content_digest(
            json.dumps(digest_data, sort_keys=True).encode()
        )

        all_fields = sorted({k for ev in events for k in ev})
        columns = {f: [ev.get(f) for ev in events] for f in all_fields}
        pa_columns = {
            n: pa.array(v, from_pandas=True)
            for n, v in columns.items()
        }
        table = pa.table(pa_columns)
        parquet_path = tmp_path / "acled_2020_2020.parquet"
        pq.write_table(table, parquet_path, compression="snappy")

        file_digest = compute_file_digest(parquet_path)

        assert content_digest != file_digest, (
            f"content={content_digest} file={file_digest} — "
            f"Parquet content and file digests must differ"
        )

    def test_year_is_cached_returns_false_due_to_mismatch(
        self, tmp_path: Path,
    ) -> None:
        """The actual bug: _year_is_cached always returns False."""
        events = [
            {"event_id_cnty": f"SOM{i:04d}", "fatalities": i * 3}
            for i in range(5)
        ]

        digest_fields = ("event_id_cnty", "fatalities")
        digest_data = sorted(
            tuple(ev.get(f, 0) for f in digest_fields)
            for ev in events
        )
        content_digest = compute_content_digest(
            json.dumps(digest_data, sort_keys=True).encode()
        )

        all_fields = sorted({k for ev in events for k in ev})
        columns = {f: [ev.get(f) for ev in events] for f in all_fields}
        pa_columns = {
            n: pa.array(v, from_pandas=True)
            for n, v in columns.items()
        }
        table = pa.table(pa_columns)
        snap_path = tmp_path / "acled_2020_2020.parquet"
        pq.write_table(table, snap_path, compression="snappy")

        ledger_path = tmp_path / "ledger.jsonl"
        append_ledger_entry(ledger_path, {
            "dataset": "acled",
            "version": "2020_2020",
            "outcome": "success",
            "content_digest": content_digest,
        })

        previous = last_digest_for_version(
            ledger_path, "2020_2020"
        )
        actual = compute_file_digest(snap_path)

        assert previous != actual, (
            f"ledger={previous} file={actual} — "
            f"content_digest vs file_digest must differ for Parquet"
        )
        # This was the bug: _year_is_cached compared these and
        # returned False, triggering a re-download.
        # Fixed in v1.2.25 by _recompute_content_digest.


class TestF3SplashZoneIsAcledOnly:
    """Probes #1, #2, #7: The splash zone is ACLED only, not 3 harvesters.

    The expert review's C-195 claimed GHS-POP and GHS-BUILT-S were
    also affected. This is wrong — their content_digest is computed
    from the same raw bytes written to disk, so
    compute_file_digest(path) == compute_content_digest(raw_bytes).

    Severity: hard falsification (of the review's splash zone)
    """

    def test_binary_file_digest_matches_content_digest(
        self, tmp_path: Path,
    ) -> None:
        for name in ("ghspop_E2020.tif", "ghsbuilts_E2020.tif"):
            data = b"\x00\x01\x02\x03" * 10000
            path = tmp_path / name
            path.write_bytes(data)

            assert compute_content_digest(data) == compute_file_digest(
                path
            ), f"{name}: content_digest should equal file_digest"
