"""Falsification test stubs: Sprint S3 regression.

Generated by /falsify on 2026-05-27.
Claim: "Sprint S3 is successfully done — no regression expected."

Each test encodes a specific falsification found during the audit.
Tests FAIL until the gap is closed.
"""

from __future__ import annotations

from pathlib import Path

REGISTER = Path("reports/technical_risk_register.md")
DEPLOY_GUIDE = Path("docs/guides/hetzner_deployment_guide.md")
PIPELINE = Path("scripts/refresh_pipeline.sh")


class TestP1RegisterStepNumbers:
    """P-1: C-138 register entry says "step 8" but actual is step 12/13.

    The C-138 Resolution field says "Run as pipeline step 8."
    The Location field references "step 7" for the health check.
    After adding V-Dem (step 8) and verify_remote_data (step 12),
    both numbers are stale. An operator reading C-138 would look
    at the wrong pipeline step.
    """

    def test_c138_resolution_step_matches_pipeline(
        self,
    ) -> None:
        assert REGISTER.exists()
        text = REGISTER.read_text()

        marker = "### C-138"
        assert marker in text, "C-138 narrative section not found"
        c138_start = text.index(marker)
        next_section = text.find("###", c138_start + len(marker))
        c138_text = (
            text[c138_start:next_section]
            if next_section != -1
            else text[c138_start:]
        )

        assert "step 8" not in c138_text, (
            "C-138 Resolution says 'step 8' but "
            "verify_remote_data.py is actually at "
            "'12/13: Verify remote data' in "
            "refresh_pipeline.sh. "
            "Fix: update C-138 Location and Resolution "
            "to reference the correct step number."
        )


class TestP2DeployGuideReferencesVerifyRemoteData:
    """P-2: Deployment guide has no reference to verify_remote_data.py.

    The deployment guide documents verify_remote.py at 5+ locations
    but has zero mentions of verify_remote_data.py. An operator
    following the guide for manual deployment would not know this
    verification step exists.
    """

    def test_deployment_guide_mentions_verify_remote_data(
        self,
    ) -> None:
        assert DEPLOY_GUIDE.exists()
        text = DEPLOY_GUIDE.read_text()
        assert "verify_remote_data" in text, (
            "Deployment guide has no reference to "
            "verify_remote_data.py. It documents "
            "verify_remote.py (connectivity/metadata) "
            "but not verify_remote_data.py (data "
            "correctness, C-138). Manual deployments "
            "following the guide would skip this check. "
            "Fix: add verify_remote_data.py to the "
            "post-deploy verification checklist."
        )
