"""Falsification tests for ADR-049 epic completeness.

Generated by /falsify on 2026-06-28. These tests fail until
the identified gaps are addressed.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


class TestF2RiskRegisterUpdated:
    """F2: Story 5 plan requires risk register update for
    spatial distribution feature."""

    def test_register_mentions_adr_049(self) -> None:
        register = (
            ROOT / "reports" / "technical_risk_register.md"
        ).read_text()
        assert "ADR-049" in register, (
            "Risk register has no mention of ADR-049 "
            "— Story 5 requires adding a concern for spatial "
            "distribution and resolving relevant entries"
        )


class TestF3ProvenanceCounters:
    """F3: ADR-049 Validation & Monitoring mandates three
    provenance counters: n_spatially_distributed,
    n_excluded_where_prec, n_passthrough_where_prec."""

    def _get_ledger_keys(self) -> set[str]:
        builder = (
            ROOT
            / "src"
            / "datafactory_viewpoint"
            / "builders"
            / "ucdp_v1.py"
        ).read_text()
        match = re.search(
            r"append_ledger_entry\(.*?\{(.*?)\}\s*\)",
            builder,
            re.DOTALL,
        )
        assert match, "Could not find append_ledger_entry call"
        return set(re.findall(r'"(\w+)":', match.group(1)))

    def test_n_excluded_where_prec_logged(self) -> None:
        keys = self._get_ledger_keys()
        assert "n_excluded_where_prec" in keys, (
            "ADR-049 §Validation requires n_excluded_where_prec "
            "in provenance ledger — counter is absent"
        )

    def test_n_passthrough_where_prec_logged(self) -> None:
        keys = self._get_ledger_keys()
        assert "n_passthrough_where_prec" in keys, (
            "ADR-049 §Validation requires n_passthrough_where_prec "
            "in provenance ledger — counter is absent"
        )


class TestF4AdrMethodConsistency:
    """F4: ADR-049 §2 table says where_prec=4 and
    where_prec=5-with-adm_1 use the adm_1 field;
    implementation uses crosswalk for all cases."""

    def _get_spatial_distribution_source(self) -> str:
        return (
            ROOT
            / "src"
            / "datafactory_viewpoint"
            / "spatial_distribution.py"
        ).read_text()

    def _get_adr_text(self) -> str:
        return (
            ROOT
            / "docs"
            / "ADRs"
            / "049_spatial_distribution_of_imprecise_ucdp_events.md"
        ).read_text()

    def test_adr_and_code_agree_on_where_prec_4_method(self) -> None:
        adr = self._get_adr_text()
        section_start = adr.find("### 2. Polygon determination")
        section_end = adr.find("### 3.", section_start)
        section_2 = adr[section_start:section_end]
        table_prescribes_adm1 = (
            "`adm_1` field from UCDP" in section_2
        )
        if table_prescribes_adm1:
            pytest.fail(
                "ADR-049 §2 table prescribes adm_1 field lookup "
                "but code uses crosswalk. Update the ADR table."
            )
