"""Falsification test stubs for DoD004 (compiler).

These tests are in TDD-red state — they FAIL against the current code.
Fix the production code to make them pass.

Generated by /falsify DoD004.
"""

from __future__ import annotations

import logging

import pytest

# --- P1: ADR-008 — strategies.get_strategy raises without logging ---


def test_get_strategy_logs_before_raising(
    caplog: pytest.LogCaptureFixture,
) -> None:
    """get_strategy must log at ERROR before raising KeyError (ADR-008)."""
    from datafactory_compilation.aggregation import get_strategy

    with (
        caplog.at_level(logging.ERROR, logger="datafactory_compilation.aggregation"),
        pytest.raises(KeyError),
    ):
        get_strategy("nonexistent_strategy")
    error_records = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert len(error_records) >= 1, (
        "ADR-008: get_strategy raises KeyError without logging at ERROR first"
    )


# --- P2: Month 13 silently maps to index 12 ---


def test_parse_month_index_rejects_month_13() -> None:
    """Month 13 is invalid — _parse_month_index must return None, not 12."""
    from datafactory_compilation.grid_compilation import _parse_month_index

    result = _parse_month_index("2024-13-01", 2024, 1)
    assert result is None, (
        f"Month 13 silently mapped to index {result}. "
        "Expected None for invalid month."
    )


def test_parse_month_index_rejects_month_0() -> None:
    """Month 0 is invalid — verify it returns None."""
    from datafactory_compilation.grid_compilation import _parse_month_index

    result = _parse_month_index("2024-00-01", 2024, 1)
    assert result is None, (
        f"Month 0 mapped to index {result}. Expected None."
    )
