"""Falsification stubs for #249 — remove consumer bridge lr_* rename.

Generated by /falsify audit. Each test encodes a soft falsification
finding that must be fixed before the claim "issue #249 is solved"
can be reasserted.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


class TestF2TransitionGuideNoFeatureRename:
    """F2: viewser_transition_guide.md side-by-side table must not
    reference FEATURE_RENAME as a current datafactory concept."""

    def test_side_by_side_table_no_feature_rename(self) -> None:
        guide = REPO_ROOT / "docs" / "guides" / "viewser_transition_guide.md"
        text = guide.read_text()
        for i, ln in enumerate(text.splitlines(), 1):
            if ln.strip().startswith("|") and "FEATURE_RENAME" in ln:
                raise AssertionError(
                    f"viewser_transition_guide.md:{i} still references "
                    f"FEATURE_RENAME: {ln.strip()}"
                )


class TestF3ExampleDocstringNoRename:
    """F3: ex_consumer_bridge.py docstring must not describe a rename
    step that no longer exists in the code."""

    def test_docstring_does_not_say_rename(self) -> None:
        example = REPO_ROOT / "examples" / "ex_consumer_bridge.py"
        text = example.read_text()
        first = text.index('"""')
        second = text.index('"""', first + 3)
        docstring = text[first:second + 3]
        assert "rename" not in docstring.lower(), (
            f"Example docstring still describes a 'rename' step "
            f"but the code no longer renames: {docstring!r}"
        )
