"""Falsification test stubs: Sprint S2 regression.

Generated by /falsify on 2026-05-27.
Claim: "Sprint S2 is successfully done — no regression expected."

Each test encodes a specific falsification found during the audit.
Tests FAIL until the gap is closed.
"""

from __future__ import annotations

from pathlib import Path

ADRS = Path("docs/ADRs")
CICS = Path("docs/CICs")


class TestP2PgidRowDirection:
    """P-2: ADR-024 PGID Convention has row direction backwards.

    ADR-024 Invariant 1 says "Axis 1: height (grid rows, south
    to north)" — row 0 is south. The code in cell_generator.py:30
    confirms: "Row-major from bottom-left: pgid = row_from_south
    * ncol + col + 1".

    But the PGID Convention section (added in S2) says "row =
    0..359 (north to south)" — opposite direction. A developer
    reading only the PGID Convention would implement the inverse
    formula with rows counting from north, shifting all spatial
    data by 180 degrees latitude.
    """

    def test_pgid_convention_row_direction_matches_invariant_1(
        self,
    ) -> None:
        adr = ADRS / "024_compilation_grid_invariants.md"
        assert adr.exists()
        text = adr.read_text()
        assert "(south to north)" in text and "row = 0..359" in text, (
            "PGID Convention says 'north to south' but "
            "Invariant 1 and cell_generator.py:30 both "
            "count rows from south (row 0 = -89.75°). "
            "Fix: change '(north to south)' to "
            "'(south to north)' in the PGID Convention."
        )


class TestP3CicFieldCount:
    """P-3: CIC README claims 21 fields, actual dataclass has 24.

    PrecomputedData has 24 @dataclass fields. The CIC table
    groups n_t/n_h/n_w/n_f into one row (21 table rows), but
    the README says "21 fields" which undercounts. The risk
    register resolution note says "22 fields" — also wrong.
    """

    def test_cic_readme_field_count_matches_code(
        self,
    ) -> None:
        readme = CICS / "README.md"
        assert readme.exists()
        text = readme.read_text()
        assert "24 fields" in text or "24-field" in text, (
            "CIC README says '21 fields' for "
            "PrecomputedData, but the actual dataclass "
            "has 24 fields (n_t, n_h, n_w, n_f are 4 "
            "separate fields grouped in 1 CIC table row). "
            "Fix: change '21 fields' to '24 fields'."
        )
